### ISSUE TITLE
Build sensu client

### ISSUE THREAD

**Issue by vanokg** [sangahco/docker-sensu#1]
How I can build sensu clinet?

> Arguments: -f docker-compose-client-dev.yml
> Command: up
> Building sensu-client
> Step 1/8 : FROM dev.sangah.com:5043/sensu-server
> ERROR: Service 'sensu-client' failed to build: Get https://dev.sangah.com:5043/v2/sensu-server/manifests/latest: no basic auth credentials

**Comment by emawind84** [comment]
first change the REGISTRY_URL with your docker hub registry, then you can use the compose with the 'dev' suffix to build and run the service.
If you want to use our build I will put it on the docker hub and change the REGISTRY_URL to our docker hun account.
Yoy can still build and publish the image on your repo anyway.

**Comment by emawind84** [comment]
I can see that the client depends on out internal build I will change it to the docker hub repository, later.

**Comment by vanokg** [comment]
>  Yoy can still build and publish the image on your repo anyway.

Thank you, I later thought to do so.
And everything turned out.
